POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "name": "admin",
    "pass": "admin"
}

###

GET http://localhost:3000/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MTU0ODY0MTl9.biTdgFCctQIrKgOpiyRAxF2NuEpXqiKMivC1FB_xzyI

###

POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "name": "lazar",
    "pass": "lazar"
}

###

DELETE  http://localhost:3000/user HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MTU0ODY2NDN9.yjPT2aoc5wRSojVHeoZZe0l9cFXgJVnSR3jd2iAzqoA

{
    "name":"lazar"
}